### ISSUE TITLE
pass --skip options to mmdebstrap

### ISSUE THREAD

**Issue by learmj** [bdrung/bdebstrap#14]
Hi,
Is there scope to provide a command line option for bdebstrap so it can pass ```--skip``` options to mmdebstrap?
This is desirable in some cases, for example to prevent mmdebstrap from including device nodes in the tarball it generates.
The device nodes that mmdebstrap creates when using unshare mode are not actually real anyway. The mmdebstrap man page states:

> In unshare mode, device nodes cannot be created.

..and in its code:
```
# If a tarball is to be created, we always (except if --skip=output/dev is
# passed) craft the /dev entries ourselves.
# Why do we put /dev entries in the final tarball?
#  - because debootstrap does it
#  - because schroot (#856877) and pbuilder rely on it and we care about
#    Debian buildds (using schroot) and reproducible builds infra (using
#    pbuilder)
# If both the above assertion change, we can stop creating /dev entries as
# well
```

A tarball created in unshare mode _without_ device nodes is able to be successfully extracted using bsdtar (or tar ```-xattrs --xattrs-include='*.*'```) when running in the appropriate namespace, but fails to extract successfully when the (fake) device nodes are present in the archive. It would be highly beneficial if they could be skipped.

Thanks for your consideration. Keep up the great work :-)
Cheers,
--  Matt

**Comment by bdrung** [comment]
Yes, bdebstrap should gain support for passing `--skip`. Patches are welcome. ;)

**Comment by learmj** [comment]
I see that tests/test_config.py has ```skip": ["check/signed-by"]``` so presumably specifying ```skip": ["output/dev"]``` would work, and mean that this could be passed to mmdebstrap via yaml.

**Comment by bdrung** [comment]
Oh, so we added the skip option in commit 92a06d6122b6a3d029b50aab65bb42d61e620d42 and released it in 0.6.0: https://github.com/bdrung/bdebstrap/releases/tag/v0.6.0

**Comment by learmj** [comment]
I tried adding the following to my yaml, but the tar ball that mmdebstrap generated still contained device nodes.
```
  skip:
    - output/dev
```
Is this the correct syntax to make this feature work?

**Comment by bdrung** [comment]
Yes, that is the correct syntax. What command does bdebstrap produce (i.e. run it in debug or verbose mode)?

**Comment by learmj** [comment]
```
  skip:
    - output/dev
```
appears in the merged config.yaml but there is no mention of skip in the initial mmdebstrap line if I invoke bdebstrap with ```-v```. At the end of execution, I see:
```
I: cleaning package lists and apt cache...
Reading package lists...
I: creating tarball...
I: done
I: removing tempdir /tmp/mmdebstrap.uvi0ymVNT_...
I: success in 80.5455 seconds
```
The tar ball still has
```
./dev/
./dev/console
...
```
mmdebstrap is running in unshare mode.

**Comment by learmj** [comment]
@bdrung I don't think this is working correctly, unless I need to do something else?

**Comment by bdrung** [comment]
It passes the parameter for me:
```sh
$ cat test.yaml 
name: test
mmdebstrap:
  skip:
    - output/dev
$ bdebstrap -c test.yaml --verbose --force
[...]
bdebstrap INFO: Calling mmdebstrap -v --skip=output/dev [...]
```

Can you share a sample bdebstrap configuration that does not work? What setup are you running on (distro, mmdebstrap version, etc)?

**Comment by learmj** [comment]
Hi @bdrung 
Sincere apologies for the very late reply. I totally missed your update. I realised the problem was caused by me having incorrect indentation in my YAML for the ```skip``` entry. It wasn't working because I had:
```
mmdebstrap:
  architectures:
    - arm64
  mode: auto
  variant: apt
  suite: bookworm
  mirrors:
    - deb xxx
    - deb yyy
skip:
  - output/dev
```
Rather than:
```
mmdebstrap:
  architectures:
    - arm64
  mode: auto
  variant: apt
  suite: bookworm
  mirrors:
    - deb xxx
    - deb yyy
  skip:
    - output/dev
```
Embarrassingly, I completely failed to notice ```bdebstrap WARNING: Ignoring unknown top level keys: skip``` at the beginning of the run. I confirm everything works fine.

**Comment by bdrung** [comment]
Great to hear that you figured out the reason. Since bdebstrap spits out a warning, there is probably nothing left to do on the bdebstrap side.
