### ISSUE TITLE
autopkgtest is failing on non-amd64 architectures

### ISSUE THREAD

**Issue by lucaskanashiro** [bdrung/bdebstrap#2]
During the `examples` test amd64 chroots are created using `bdebstrap` but it is failing in Ubuntu on all architectures except amd64. Below you can check the log for arm64 (it is the same error for other architectures):

https://autopkgtest.ubuntu.com/results/autopkgtest-impish/impish/arm64/b/bdebstrap/20210525_230527_e7662@/log.gz

I tried to simply add `arch-test` as a test dependency but this is not enough. Maybe we want to identify the host architecture and run `sed` against the example files to use it instead of always amd64? It is not clear to me if this setup of a chroot using a foreign architecture is intentional, if this is a use case you really want to cover.

**Comment by bdrung** [comment]
It's not intentional to test foreign architecture. So can you test passing the host architecture to the bdebstrap call as `--architectures`? Otherwise I could just drop the architecture from the example to use the host architecture.

**Comment by bdrung** [comment]
The problem arises when using the Debian live system example. It lists `linux-image-cloud-amd64` as package dependency and that is architecture dependent.

**Comment by bdrung** [comment]
After several tweaks and tests in my PPA, all architectures successfully run the autopkgtest, except for i386:
```
The following packages have unmet dependencies:
 builddeps:[...]/2-autopkgtest-satdep.dsc:i386 : Depends: squashfs-tools-ng:i386 but it is not installable
                                                 Depends: bdebstrap:i386 but it is not installable
```

I will upload the fixed package to Debian unstable.

**Comment by lucaskanashiro** [comment]
Thanks for tackling this issue @bdrung ! I'll be syncing the new version into Ubuntu when it lands in Debian.

**Comment by bdrung** [comment]
Too late. All autopkgtest for bdebstrap 0.1.2-1 on Debian succeed. So I synced bdebstrap 0.1.2-1 now to Ubuntu.
